### ISSUE TITLE
FakeDetector: C:\Python27\python.exe: can't open file 'L': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ScouseTS** [nzbget/FakeDetector#5]
Hi,

I've just noticed my nzbget is falling over due to Fake detector for some odd reason, when I look in logs it says the below:

"FakeDetector: C:\Python27\python.exe: can't open file 'L': [Errno 2] No such file or directory"

Thanks,
Ste

**Comment by hugbug** [comment]
Do other scripts work?
Nzbget version?
Please try the latest testing release, use debug version (from github releases page), activate all logging options (DebugTarget=log, etc.). Then, after the error, send me the log-file to nzbget@gmail.com.

**Comment by hugbug** [comment]
Closing this due to lack of feedback. Feel free to comment and reopen with more info.
